package com.XZY_SUNSHINE.crm.workbench.activity.mapper;

import com.XZY_SUNSHINE.crm.workbench.activity.pojo.ActivityRemark;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;
@Mapper
public interface ActivityRemarkMapper {
    List<ActivityRemark> selectActivityRemarkForDetailByActivityId(String id);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_activity_remark
     *
     * @mbggenerated Tue Apr 18 13:54:07 CST 2023
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_activity_remark
     *
     * @mbggenerated Tue Apr 18 13:54:07 CST 2023
     */
    int insert(ActivityRemark record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_activity_remark
     *
     * @mbggenerated Tue Apr 18 13:54:07 CST 2023
     */
    int insertSelective(ActivityRemark record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_activity_remark
     *
     * @mbggenerated Tue Apr 18 13:54:07 CST 2023
     */
    ActivityRemark selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_activity_remark
     *
     * @mbggenerated Tue Apr 18 13:54:07 CST 2023
     */
    int updateByPrimaryKeySelective(ActivityRemark record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_activity_remark
     *
     * @mbggenerated Tue Apr 18 13:54:07 CST 2023
     */
    int updateByPrimaryKey(ActivityRemark record);
}