package com.XZY_SUNSHINE.crm.workbench.activity.mapper;

import com.XZY_SUNSHINE.crm.workbench.activity.pojo.Activity;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;
import java.util.Map;

@Mapper
public interface ActivityMapper {
    int insertActivityByList(List<Activity> activities);
    List<Activity> selectAllActivitiesByIds(String[] ids);
    List<Activity> selectAllActivities();
    int deleteActivityByIds(String[] ids);
    int selectActivityByConditionForCounts(Map map);
    List<Activity> selectActivityByConditionForPage(Map map);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_activity
     *
     * @mbggenerated Thu Apr 13 15:33:25 CST 2023
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_activity
     *
     * @mbggenerated Thu Apr 13 15:33:25 CST 2023
     */
    int insert(Activity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_activity
     *
     * @mbggenerated Thu Apr 13 15:33:25 CST 2023
     */
    int insertSelective(Activity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_activity
     *
     * @mbggenerated Thu Apr 13 15:33:25 CST 2023
     */
    Activity selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_activity
     *
     * @mbggenerated Thu Apr 13 15:33:25 CST 2023
     */
    int updateByPrimaryKeySelective(Activity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_activity
     *
     * @mbggenerated Thu Apr 13 15:33:25 CST 2023
     */
    int updateByPrimaryKey(Activity record);
}