package com.XZY_SUNSHINE.crm.workbench.Tran.mapper;

import com.XZY_SUNSHINE.crm.workbench.Tran.pojo.TranHistory;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface TranHistoryMapper {
    List<TranHistory> selectTranHistoryForDetailByTranId(String id);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_tran_history
     *
     * @mbggenerated Sat Apr 22 14:07:31 CST 2023
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_tran_history
     *
     * @mbggenerated Sat Apr 22 14:07:31 CST 2023
     */
    int insert(TranHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_tran_history
     *
     * @mbggenerated Sat Apr 22 14:07:31 CST 2023
     */
    int insertSelective(TranHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_tran_history
     *
     * @mbggenerated Sat Apr 22 14:07:31 CST 2023
     */
    TranHistory selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_tran_history
     *
     * @mbggenerated Sat Apr 22 14:07:31 CST 2023
     */
    int updateByPrimaryKeySelective(TranHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_tran_history
     *
     * @mbggenerated Sat Apr 22 14:07:31 CST 2023
     */
    int updateByPrimaryKey(TranHistory record);
}