package com.XZY_SUNSHINE.crm.workbench.Tran.mapper;

import com.XZY_SUNSHINE.crm.workbench.Tran.pojo.TranRemark;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;
@Mapper
public interface TranRemarkMapper {
    int insertByList(List<TranRemark> tranRemarkList);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_tran_remark
     *
     * @mbggenerated Sat Apr 22 14:08:04 CST 2023
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_tran_remark
     *
     * @mbggenerated Sat Apr 22 14:08:04 CST 2023
     */
    int insert(TranRemark record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_tran_remark
     *
     * @mbggenerated Sat Apr 22 14:08:04 CST 2023
     */
    int insertSelective(TranRemark record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_tran_remark
     *
     * @mbggenerated Sat Apr 22 14:08:04 CST 2023
     */
    TranRemark selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_tran_remark
     *
     * @mbggenerated Sat Apr 22 14:08:04 CST 2023
     */
    int updateByPrimaryKeySelective(TranRemark record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_tran_remark
     *
     * @mbggenerated Sat Apr 22 14:08:04 CST 2023
     */
    int updateByPrimaryKey(TranRemark record);
}