package com.XZY_SUNSHINE.crm.workbench.clue.mapper;

import com.XZY_SUNSHINE.crm.workbench.clue.pojo.ClueRemark;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;
@Mapper
public interface ClueRemarkMapper {
    int deleteByClueId(String clueId);
    List<ClueRemark> selectClueRemarkByClueIdForConvert(String id);
    List<ClueRemark> selectClueRemarkByClueId(String id);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_clue_remark
     *
     * @mbggenerated Wed Apr 19 08:37:24 CST 2023
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_clue_remark
     *
     * @mbggenerated Wed Apr 19 08:37:24 CST 2023
     */
    int insert(ClueRemark record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_clue_remark
     *
     * @mbggenerated Wed Apr 19 08:37:24 CST 2023
     */
    int insertSelective(ClueRemark record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_clue_remark
     *
     * @mbggenerated Wed Apr 19 08:37:24 CST 2023
     */
    ClueRemark selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_clue_remark
     *
     * @mbggenerated Wed Apr 19 08:37:24 CST 2023
     */
    int updateByPrimaryKeySelective(ClueRemark record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_clue_remark
     *
     * @mbggenerated Wed Apr 19 08:37:24 CST 2023
     */
    int updateByPrimaryKey(ClueRemark record);
}