package com.XZY_SUNSHINE.crm.workbench.clue.mapper;

import com.XZY_SUNSHINE.crm.workbench.clue.pojo.Clue;

import java.util.List;
import java.util.Map;

public interface ClueMapper {
    int selectCluesForPageCounts(Map map);
     List<Clue> selectCluesForPage(Map map);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_clue
     *
     * @mbggenerated Wed Apr 19 08:36:04 CST 2023
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_clue
     *
     * @mbggenerated Wed Apr 19 08:36:04 CST 2023
     */
    int insert(Clue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_clue
     *
     * @mbggenerated Wed Apr 19 08:36:04 CST 2023
     */
    int insertSelective(Clue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_clue
     *
     * @mbggenerated Wed Apr 19 08:36:04 CST 2023
     */
    Clue selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_clue
     *
     * @mbggenerated Wed Apr 19 08:36:04 CST 2023
     */
    int updateByPrimaryKeySelective(Clue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_clue
     *
     * @mbggenerated Wed Apr 19 08:36:04 CST 2023
     */
    int updateByPrimaryKey(Clue record);
}