package com.XZY_SUNSHINE.crm.workbench.clue.mapper;

import com.XZY_SUNSHINE.crm.workbench.clue.pojo.DicValue;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;
@Mapper
public interface DicValueMapper {
    List<DicValue> selectDicValueByTypeCode(String appellation);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_value
     *
     * @mbggenerated Wed Apr 19 08:41:30 CST 2023
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_value
     *
     * @mbggenerated Wed Apr 19 08:41:30 CST 2023
     */
    int insert(DicValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_value
     *
     * @mbggenerated Wed Apr 19 08:41:30 CST 2023
     */
    int insertSelective(DicValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_value
     *
     * @mbggenerated Wed Apr 19 08:41:30 CST 2023
     */
    DicValue selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_value
     *
     * @mbggenerated Wed Apr 19 08:41:30 CST 2023
     */
    int updateByPrimaryKeySelective(DicValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_value
     *
     * @mbggenerated Wed Apr 19 08:41:30 CST 2023
     */
    int updateByPrimaryKey(DicValue record);
}