package com.XZY_SUNSHINE.crm.workbench.Contacts.mapper;

import com.XZY_SUNSHINE.crm.workbench.Contacts.pojo.ContactsRemark;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface ContactsRemarkMapper {
    int insertByList(List<ContactsRemark> contactsRemarkList);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_contacts_remark
     *
     * @mbggenerated Sat Apr 22 12:51:54 CST 2023
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_contacts_remark
     *
     * @mbggenerated Sat Apr 22 12:51:54 CST 2023
     */
    int insert(ContactsRemark record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_contacts_remark
     *
     * @mbggenerated Sat Apr 22 12:51:54 CST 2023
     */
    int insertSelective(ContactsRemark record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_contacts_remark
     *
     * @mbggenerated Sat Apr 22 12:51:54 CST 2023
     */
    ContactsRemark selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_contacts_remark
     *
     * @mbggenerated Sat Apr 22 12:51:54 CST 2023
     */
    int updateByPrimaryKeySelective(ContactsRemark record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_contacts_remark
     *
     * @mbggenerated Sat Apr 22 12:51:54 CST 2023
     */
    int updateByPrimaryKey(ContactsRemark record);
}